[book]
authors = ["Connor Horman"]
language = "en-US"
multilingual = false
src = "src"
title = "Connor Horman's Writing"

[preprocessor.links]

[preprocessor.add-copyright]
exclude=["COPYRIGHT.md"]

[preprocessor.add-copyright.epub-fancy]
include=[]


[output.markdown]

[output.html]


[output.epub-fancy]
optional=true
output=["part","full"]
always-include=["COPYRIGHT.md","COPYRIGHT-STUB.md"]

[output.epub-fancy.file-ids]