[book]
authors = ["Connor Horman"]
language = "en"
multilingual = false
src = "src"
title = "Connor Horman's Writing"

[preprocessor.links]

[preprocessor.add-copyright]
exclude=["COPYRIGHT.md"]

[preprocessor.add-copyright.markdown]


[output.markdown]

[output.html]


[output.epub-fancy]
optional=true